version: '2'

services:
  frontend:
    image: index.docker.io/buildkite/frontend
    build: .
    environment:
      - EMOJI_HOST
      - FRONTEND_HOST
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_PIPELINE_SLUG
      - CI
    volumes:
      - ".:/frontend:cached"
      - /frontend/node_modules
