version: '2'

services:
  frontend:
    build: .
    volumes:
      - "./bundle-analysis:/frontend/bundle-analysis"
      - "./dist:/frontend/dist"
      - "./coverage:/frontend/coverage"
    environment:
      BUILDKITE:
      BUILDKITE_COMMIT:
      BUILDKITE_ORGANIZATION_SLUG:
      BUILDKITE_PIPELINE_SLUG:
      CI:
      EMOJI_HOST:
      FRONTEND_HOST:
