steps:
  - name: ":eslint:"
    command: ".buildkite/eslint.sh"
    plugins:
      docker-compose#e8ce6c1:
        run: frontend

  - name: ":webpack:"
    command: ".buildkite/webpack.sh"
    artifact_paths: "dist/*"
    plugins:
      docker-compose#e8ce6c1:
        run: frontend
    env:
      NODE_ENV: production

  - wait

  - name: ":rocket:"
    command: ".buildkite/deploy.sh"
    branches: "master"
    artifact_paths: "tmp/verify/*"
    agents:
      queue: "deploy"
