steps:
  - wait

  - name: ":npm:"
    command: ".buildkite/npm.sh"
    concurrency: 1
    concurrency_group: "npmer"

  - wait

  - name: ":eslint:"
    command: ".buildkite/eslint.sh"

  - name: ":webpack:"
    command: ".buildkite/webpack.sh"
    artifact_paths: "dist/*"
    env:
      NODE_ENV: production

  - wait

  - name: ":rocket:"
    command: ".buildkite/deploy.sh"
    artifact_paths: "dist/*"
    branches: "master"
    agents:
      queue: "deploy"
