steps:
  - name: ":npm:"
    command: >
            echo "--- Installing :npm: packages"
            rm -r node_modules
            npm-cache install npm
    concurrency: 1
    concurrency_group: "npmer"

  - wait

  - name: ":eslint:"
    command: >
            echo "--- Installing :npm: packages"
            rm -rf node_modules
            npm-cache install npm

            echo "--- Running eslint :eslint:"
            ./node_modules/eslint/bin/eslint.js
