steps:
  - wait

  - name: ":npm:"
    command: "rm -r node_modules; npm-cache install npm"
    concurrency: 1
    concurrency_group: "npmer"

  - wait

  - name: ":eslint:"
    command: ".buildkite/eslint.sh"

  - name: ":webpack:"
    command: ".buildkite/webpack.sh"
    env:
      NODE_ENV: "production"
      WEBPACK_HOST: "/dist/"
      EMOJI_HOST: "/emojis/"
